### ISSUE TITLE
16. Obcięte znaczenia fiszek #616 #478 #617 

### ISSUE THREAD

**Issue by kb9997** [TrolleyDilemma/Fiszki#24]
[Fashcards_Issue_1.pdf](https://github.com/TrolleyDilemma/Fiszki/files/2612716/Fashcards_Issue_1.pdf)
[Fashcards_Issue_2.pdf](https://github.com/TrolleyDilemma/Fiszki/files/2612717/Fashcards_Issue_2.pdf)
[Fashcards_Issue_3.pdf](https://github.com/TrolleyDilemma/Fiszki/files/2612718/Fashcards_Issue_3.pdf)

**Comment by Szaman97** [comment]
Bugi zostaną naprawione przy okazji weryfikacji całego słownictwa.
